version: '2'

# Sección de servicios
services:
  peer-base: #Configurable
    image: hyperledger/fabric-peer:2.2.0 #Imagen de Hyperledger Fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      # ---CHANGED---
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fiuba-network_basic  #Nombre red de docker-compose
      - FABRIC_LOGGING_SPEC=INFO #Nivel de log
     # - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true #Levantar con TLS (Modo seguro)
      #Protocolo gossip
      - CORE_PEER_GOSSIP_USELEADERELECTION=true 
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      #Rutas donde se montaran los certificados en el contenedor
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    #Directorio de trabajo
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #Comando que se ejecuta. Programa peer para inicir el nodo
    command: peer node start
